#!/bin/bash

echo "Starting the new server setup script"
cd ~

# Update the system
sudo apt-get update && sudo apt-get upgrade -y


echo ""
echo "Installing unattended-upgrades..."
# Install and setup unattended-upgrades
sudo apt-get install unattended-upgrades -y

# Edit the 50unattended-upgrade file
sudo cat >/etc/apt/apt.conf.d/50unattended-upgrades <<EOL
// Automatically upgrade packages from these (origin:archive) pairs
Unattended-Upgrade::Allowed-Origins {
        "${distro_id}:${distro_codename}-security";
        "${distro_id}:${distro_codename}-updates";
//      "${distro_id}:${distro_codename}-proposed";
//      "${distro_id}:${distro_codename}-backports";
};

// List of packages to not update (regexp are supported)
Unattended-Upgrade::Package-Blacklist {
//      "vim";
//      "libc6";
//      "libc6-dev";
//      "libc6-i686";
};

// This option allows you to control if on a unclean dpkg exit
// unattended-upgrades will automatically run
//   dpkg --force-confold --configure -a
// The default is true, to ensure updates keep getting installed
Unattended-Upgrade::AutoFixInterruptedDpkg "true";

// Split the upgrade into the smallest possible chunks so that
// they can be interrupted with SIGUSR1. This makes the upgrade
// a bit slower but it has the benefit that shutdown while a upgrade
// is running is possible (with a small delay)
//Unattended-Upgrade::MinimalSteps "true";

// Install all unattended-upgrades when the machine is shuting down
// instead of doing it in the background while the machine is running
// This will (obviously) make shutdown slower
//Unattended-Upgrade::InstallOnShutdown "true";

// Send email to this address for problems or packages upgrades
// If empty or unset then no email is sent, make sure that you
// have a working mail setup on your system. A package that provides
// 'mailx' must be installed. E.g. "user@example.com"
//Unattended-Upgrade::Mail "root";

// Set this value to "true" to get emails only on errors. Default
// is to always send a mail if Unattended-Upgrade::Mail is set
//Unattended-Upgrade::MailOnlyOnError "true";

// Do automatic removal of new unused dependencies after the upgrade
// (equivalent to apt-get autoremove)
Unattended-Upgrade::Remove-Unused-Dependencies "true";

// Automatically reboot *WITHOUT CONFIRMATION*
//  if the file /var/run/reboot-required is found after the upgrade
Unattended-Upgrade::Automatic-Reboot "true";

// If automatic reboot is enabled and needed, reboot at the specific
// time instead of immediately
//  Default: "now"
//Unattended-Upgrade::Automatic-Reboot-Time "02:00";

// Use apt bandwidth limit feature, this example limits the download
// speed to 70kb/sec
//Acquire::http::Dl-Limit "70";
EOL

# Edit the 10periodic file
sudo cat >/etc/apt/apt.conf.d/10periodic <<EOL
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
APT::Periodic::Unattended-Upgrade "1";
EOL

/etc/init.d/unattended-upgrades restart


echo ""
echo "Installing fail2ban for SSHD..."
# Install and setup fail2ban for SSHD
sudo apt-get install fail2ban -y
# Copy the default jail.conf file to a new file called jail.local
sudo cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
# Change the ban time from 600 seconds (10 min) to 86,400 seconds (1 day) :)
perl -pi -e 's/bantime  = 600/bantime  = 86400/g' /etc/fail2ban/jail.local
# Change the find time from 600 seconds (10 min) to 3,600 seconds (1 hour)
perl -pi -e 's/findtime  = 600/findtime  = 3600/g' /etc/fail2ban/jail.local
sudo service fail2ban restart


echo ""
echo "Enabling ufw firewall, only allowing ssh (port 22)..."
# Enable and set the ufw firewall for ssh
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw --force enable


# Create a new system user with sudo access
echo ""
read -e -p "Enter the username you want to use: " new_username
grep "^$new_username" /etc/passwd > /dev/null
if [ $? -eq 0 ]; then
    echo "$new_username already exists"
    echo "The user was not changed"
else
    # Create the new user account
    sudo adduser $new_username
    # The user will be prompted to enter their password
    # Enable the user to have sudo access
    sudo usermod -aG sudo $new_username
fi


echo ""
echo "Disabling root based login..."
# Before disabling root login, ensure a non root user exist
perl -pi -e 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
sudo service ssh restart


echo ""
echo "Do you already have an SSH key pair linked to the main user account on this server?"
select yn in "Yes" "No"
do
    case $yn in
        Yes )
            echo "Disabling password based login..."
            perl -pi -e 's/PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
            sudo service ssh restart
            break
            ;;
        No )
            echo "Password based login is still enabled."
            echo ""
            echo "Add an ssh key pair for your user. View this link for help adding a ssh key:"
            echo "https://github.com/camisatx/Guides/blob/master/Ubuntu_Commands.md#ssh-key"
            echo ""
            echo "Once complete, disable password based login by running the following two lines:"
            echo "perl -pi -e 's/PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config"
            echo "sudo service ssh restart"
            echo ""
            break
            ;;
     esac
done


echo ""
echo "Installing Maldet..."
# Download and install Maldet (LMD)
cd /usr/local/src/
sudo wget http://www.rfxn.com/downloads/maldetect-current.tar.gz
sudo tar -xzf maldetect-current.tar.gz
cd maldetect-*
sudo sh ./install.sh
cd ..
# Delete original download zip files
sudo rm -rf maldetect-current.tar.gz
sudo rm -rf maldetect-*
cd ~

# Enable the LMD quarantine by replacing these 0's with 1's
perl -pi -e 's/quarantine_hits="0"/quarantine_hits="1"/g' /usr/local/maldetect/conf.maldet
perl -pi -e 's/quarantine_clean="0"/quarantine_clean="1"/g' /usr/local/maldetect/conf.maldet


echo ""
echo "Installing ClamAV..."
# Install ClamAV
sudo apt-get install clamtk clamav -y

echo ""
echo "Testing Maldet with ClamAV..."
sudo maldet -d
sudo maldet -u


echo ""
echo "Finished setting up the server"
echo "Have fun!"